### ISSUE TITLE
wx.chooseImage()唤起失败

### ISSUE THREAD

**Issue by milobluebell** [zhaoky/wx-jssdk-ts#1]
老铁
`
			wx.chooseImage({
				count: 9,
				success: (imgs: any)=> {
					console.log(imgs, '正确了');
				},
				cancel: ()=> {
					console.log('出错了');
				},
                         });
`
这种方式，在HUAWEI机安卓系统上，无法正常唤起小程序的选择图片。可以排查一下试试么

**Comment by zhaoky** [comment]
@milobluebell 兄弟，只在华为上有问题么？那应该是兼容性问题

**Comment by milobluebell** [comment]
@zhaoky  ios我没有试，据segmentfault上说也不行。我搜了一下有可能是因为微信小程序只允许公众号的webview调用wx.chooseImage()，而小程序内不允许调用⬇️

[sf链接](https://segmentfault.com/q/1010000008289307#a-1020000009071100)

**Comment by zhaoky** [comment]
小程序里用wxsdk的方法么？那肯定很多都不行的，只有部分可以：https://developers.weixin.qq.com/miniprogram/dev/component/web-view.html
