### ISSUE TITLE
更新到1.6.0版本

### ISSUE THREAD

**Issue by ethanyou725** [zhaoky/wx-jssdk-ts#2]
https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/Wechat_Open_Tag.html
https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/JS-SDK.html#63
增加了wx.config 增加了 openTagList

**Comment by zhaoky** [comment]
已合pr并发布npm，后续有问题请提继续提issues或pr，谢谢支持。 #3

**Comment by zhaoky** [comment]
npm地址：https://www.npmjs.com/package/weixin-js-sdk-ts
